IF(SELECT TOP 1 1 FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME = 'TB_CALC_CUSTO') IS NOT NULL
BEGIN
	DROP TABLE [DBO].[TB_CALC_CUSTO]
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [DBO].[TB_CALC_CUSTO](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[SEGMENTO] [VARCHAR](10),
PRIMARY KYE CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NOECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

GRANT SELECT, INSERT, DELETE, UPDATE ON [DBO].[TB_CALC_CUSTO] TO GSH800