USE DBSH804
GO

DECLARE @DATAATUAL AS DATETIME = GETDATE()
DECLARE @ORIGEMCAMPO AS INT = 40
DECLARE @USUARIO AS VARCHAR(20) = 'GOSOSIL'

IF(SELECT TOP 1 1 FROM [TB_PARAMETRO_CAMPOVALIDADOR]
   WHERE NOME_CAMPO = 'FALTA_BASE_CLUSTER' AND ORIGEM_CAMPO = @ORIGEMCAMPO) IS NULL
BEGIN
INSERT INTO [DBO].[TB_PARAMETRO_CAMPOVALIDADOR]
			([NOME_CAMPO],
			 [ORIGEM_CAMPO],
			 [TIPO_CAMPO],
			 [USUARIO_ULTIMA_ALTERACAO],
			 [DATA_ULTIMA_ALTERACAO])
		VALUES
			('FALTA_BASE_CLUSTER', @ORIGEMCAMPO, 1, @USUARIO, @DATAATUAL)