IF(SELECT TOP 1 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('[DBO].[TB_VISAO_CLIENTE]') AND NAME = 'DESC_AVAL_ALCADA_3') IS NOT NULL 
ALTER TABLE [TB_VISAO_CLIENTE] DROP COLUMN DESC_AVAL_ALCADA_3

ALTER TABLE [TB_VISAO_CLIENTE] ADD DESC_AVAL_ALCADA_3 VARCHAR(50) NULL