USE DBSH804
GO

-- DECLARE @STARTDATE DATETIME = '2021-11-16';
-- DECLARE @ENDDATE DATETIME = '2021-11-17';
-- SELECT [DBO].Function_DiasUteisEntreDatas(@STARTDATE, @ENDDATE) AS 'QTD_DIAS_UTEIS'

IF(	SELECT TOP 1 1 FROM SYSOBJECTS 
	WHERE ID = OBJECT_ID(N'[DBO].[Function_DiasUteisEntreDatas]')) IS NOT NULL
BEGIN
	DROP FUNCTION [DBO].[Function_DiasUteisEntreDatas];
END
GO

CREATE FUNCTION [DBO].[Function_DiasUteisEntreDatas] (@STARTDATE DATETIME, @ENDDATE DATETIME)
RETURNS INT 
AS
BEGIN

	DECLARE @RETORNO INT = 0;
	
	IF((@STARTDATE IS NOT NULL) AND (@ENDDATE IS NOT NULL) AND (@ENDDATE >= @STARTDATE))
	BEGIN
		DECLARE TOTALDAYS INT = DATEDIFF(DAY, @STARTDATE-1, @ENDDATE);
		
		DECLARE @WEEKENDDAYS INT = ((DATEDIFF(WEEK, @STARTDATE, @ENDDATE) * 2)
											CASE WHEN DATEPART(WEEKDAY, @STARTDATE) = 1 THEN 1 ELSE 0 END + 
											CASE WHEN DATEPART(WEEKDAY, @ENDDATE) = 7 THEN 1 ELSE 0 END);
		
		DECLARE @FERIADOS INT = (SELECT COUNT(*) FROM TB_FERIADO WHERE DATA BETWEEN @STARTDATE AND @ENDDATE AND DIA_SEMANA NOT IN ('SÁBADO', 'DOMINGO'))
		
		SET @RETORNO = @TOTALDAYS - @WEEKENDDAYS - @FERIADOS
	END
	
	RETURN @RETORNO
END 
GO

GRANT EXECUTE ON [DBO].[Function_DiasUteisEntreDatas] TO GSH800

-- CRIAR UMA TABELA PARA ARMAZENAR OS FERIADOS DO ANO EM QUESTÃO ATÉ 2080
-- CAMPOS DATA PK DATETIME NOT NULL, DIA_SEMANA VARCHAR(20) NULL, DESCRICAO VARCHAR(50) NULL

